In [1]:
import numpy as np

In [2]:
# create a 1D array
x = np.array([0, 1, 2, 3, 4, 5, 6])

In [3]:
# find all non-zero elements in x
non_zero_elements = x[x!=0]

# find the non-zero elements indices in x, i.e. the position.
non_zero_elements_indices  = np.nonzero(x)

# check the result
print ('The non_zero_elements are:', non_zero_elements)
print ('The non_zero_elements indices are:', non_zero_elements_indices)

The non_zero_elements are: [1 2 3 4 5 6]
The non_zero_elements indices are: (array([1, 2, 3, 4, 5, 6], dtype=int32),)


In [4]:
# create a 5x5 matrix A with random numbers
A = np.random.randn(5, 5)

# create a 5x5 identity matrix B
B = np.eye(5)

# show the matrix A and B
print ('The matrix A is:\n', A)
print ('The matrix B is:\n', B)

The matrix A is:
 [[ 1.76125212 -1.18551762 -1.06211496  0.9022337  -0.41940025]
 [ 0.0901296   1.24068819  0.05977449 -1.14023988  0.48982464]
 [-0.97958245 -0.0021547   1.79822657 -0.04272431  0.72060667]
 [ 0.55189202 -0.05843421 -1.20288563 -0.60561163 -1.48877413]
 [ 0.1285736   0.16884    -0.40008242  1.19793117 -0.21282754]]
The matrix B is:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# calculate the following equations

# A + B
addition = A + B
# show addition result
print ('The addition result is:\n', addition)

# A - B
subtraction = A - B
# show subtraction result
print ('The subtraction result is:\n', subtraction)

# A * B (matrix product)
product = np.dot(A,B)
# show product result
print ('The product result is:\n', product)

# A' (transpose of A)
# Calculate the transpose and show the result
print ('The tranpose result is:\n', A.T,)

The addition result is:
 [[ 2.76125212e+00 -1.18551762e+00 -1.06211496e+00  9.02233697e-01
  -4.19400252e-01]
 [ 9.01296000e-02  2.24068819e+00  5.97744899e-02 -1.14023988e+00
   4.89824642e-01]
 [-9.79582447e-01 -2.15470398e-03  2.79822657e+00 -4.27243148e-02
   7.20606673e-01]
 [ 5.51892018e-01 -5.84342150e-02 -1.20288563e+00  3.94388366e-01
  -1.48877413e+00]
 [ 1.28573596e-01  1.68839998e-01 -4.00082415e-01  1.19793117e+00
   7.87172464e-01]]
The subtraction result is:
 [[ 0.76125212 -1.18551762 -1.06211496  0.9022337  -0.41940025]
 [ 0.0901296   0.24068819  0.05977449 -1.14023988  0.48982464]
 [-0.97958245 -0.0021547   0.79822657 -0.04272431  0.72060667]
 [ 0.55189202 -0.05843421 -1.20288563 -1.60561163 -1.48877413]
 [ 0.1285736   0.16884    -0.40008242  1.19793117 -1.21282754]]
The product result is:
 [[ 1.76125212 -1.18551762 -1.06211496  0.9022337  -0.41940025]
 [ 0.0901296   1.24068819  0.05977449 -1.14023988  0.48982464]
 [-0.97958245 -0.0021547   1.79822657 -0.04272431  0.72

In [6]:
# calculate the mean, sum, max, min value for each column in A

# Mean for each column
A_mean_col = A.mean(axis=0)
print ('The mean for each column:\n', A_mean_col)

# Sum for each column
A_sum_col = A.sum(axis=0)
print ('The sum for each column:\n', A_sum_col)

# Max for each column
A_max_col = A.max(axis=0)
print ('The max for each column:\n', A_max_col)

# Min for each column
A_min_col = A.min(axis=0)
print ('The min for each column:\n', A_min_col)

The mean for each column:
 [ 0.31045298  0.03268433 -0.16141639  0.06231781 -0.18211412]
The sum for each column:
 [ 1.55226489  0.16342165 -0.80708194  0.31158904 -0.9105706 ]
The max for each column:
 [1.76125212 1.24068819 1.79822657 1.19793117 0.72060667]
The min for each column:
 [-0.97958245 -1.18551762 -1.20288563 -1.14023988 -1.48877413]


In [7]:
# normalize A with its max value A_max and min value A_min
# i.e., for any value x in A,
# x = (x - A_min) / (A_max - A_min)
A_max = np.max(A)
A_min = np.min(A)
A = (A - A_min)/(A_max - A_min)
print ('The max value in A is:', A_max)
print ('The min value in A is:', A_min)
print ('The normalize form is:\n', A)

The max value in A is: 1.798226573069576
The min value in A is: -1.4887741300127448
The normalize form is:
 [[0.98875131 0.09225934 0.12980197 0.72741324 0.32533424]
 [0.48034785 0.83038082 0.47111296 0.10603413 0.60194656]
 [0.15491073 0.45227232 1.         0.43992988 0.67215708]
 [0.62082924 0.43515047 0.08697549 0.26868339 0.        ]
 [0.49204362 0.50429382 0.33121128 0.8173729  0.38817959]]


In [8]:
# advanced exercise
# solve the system of equations:
# 3 * x0 + x1 = 9
# x0 + 2 * x1 = 8

# Ax = b 
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [9]:
# compare x with the product of inverse A and b
# calculate the inverse of A
A_inv = np.linalg.inv(A)

# product of inverse A and B 
product_invA_B = np.dot(A_inv,b)

# comapre x with the "product of inverse A and b"
compare = np.subtract(x, product_invA_B)

# print the result
print ('The comparation of x with the product of inverse A and b:', compare)


The comparation of x with the product of inverse A and b: [2.22044605e-16 0.00000000e+00]
